# Puerto de expocision
server:
    port: ${SERVER_PORT:8097}

# Configuraicon Spring Boot
spring:
    application:
        name: vg-ms-assignmentStaff
    data:
        mongodb:
            uri: mongodb+srv://amirarbieto:n1230IGFtm6682Kj@artemiosolutions.pripjnm.mongodb.net/artemiosolutions?retryWrites=true&w=majority

# Microservice health meter
management:
  endpoint:
    health:
      show-details: always

# Empoit de actuator  

api:
   version: api/v1

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api/AssignmentStaff

# servicos externos 
services:
  didactic-unit:
    url:  ${DIDACTIC_UNIT_SERVICE_URL:https://vg-ms-didactic-unit-production.up.railway.app/common/api/v1/didactic-unit}
  institucional-staff:
    url:  ${INSTITUCIONAL_STAFF_SERVICE_URL:https://vg-ms-institucional-staff-production-4fb6.up.railway.app/management/api/v1/institucional-staff}
